{
 "title": "IoT dashboard V3",
 "time": { "from": "2024-01-01T09:20:00.000Z", "to": "2024-01-01T17:30:00.000Z" },
 "panels": [
  {
   "title": "Température",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature_c FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, temperature_c FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pression",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pressure_raw_hpa FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pression",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, pressure_raw_hpa FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT humidity_percent FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, humidity_percent FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Irradiation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT irradiation_w_per_m2 FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Irradiation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, irradiation_w_per_m2 FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dew Point (C)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dewpoint_c FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dew Point (Point de rosée)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, dewpoint_c FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pluie (mm)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT rain_mm FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pluie (mm)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, rain_mm FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Wet bulb temperature",
   "type": "gauge",
   "description": "Température du thermomètre mouillé",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temperature_wetbulb_stull2011_c FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Wet bulb temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, temperature_wetbulb_stull2011_c FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Battery (V)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT battery_v FROM info_csv LIMIT 50 "
    }
   ]
  },
  {
   "title": "Battery (V)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT time_utc, battery_v FROM info_csv LIMIT 50 "
    }
   ]
  }
 ]
}